package com.codependentvariables.aiandme.model.dao;

import com.codependentvariables.aiandme.database.*;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Logger;

public abstract class BaseSqliteDAO {
    private static final Logger logger = Logger.getLogger(BaseSqliteDAO.class.getName());

    /**
     * For executing SQL without getting back generated keys, e.g. update or delete.
     * @param sql SQL to execute
     * @param preparedStatementBinder Function with context of PreparedStatement
     */
    protected void executeSql(String sql, IPreparedStatementBinder preparedStatementBinder) {
        Connection connection = SqliteConnection.getConnection();
        try (PreparedStatement preparedStatement = connection.prepareStatement(sql, Statement.NO_GENERATED_KEYS)) {
            preparedStatementBinder.accept(preparedStatement);
            logger.info(String.format("Executing SQL: %s", preparedStatement.toString()));
            preparedStatement.executeUpdate();
        } catch (SQLException e) {
            throw handleException(sql, e);
        }
    }

    /**
     * For executing SQL, getting back a generated key, e.g. create.
     * @param sql SQL to execute
     * @param preparedStatementBinder Function with context of PreparedStatement
     * @return The generated key
     */
    protected int executeSqlWithGeneratedKeys(String sql, IPreparedStatementBinder preparedStatementBinder) {
        Connection connection = SqliteConnection.getConnection();
        try (PreparedStatement preparedStatement = connection.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {
            preparedStatementBinder.accept(preparedStatement);
            logger.info(String.format("Executing SQL: %s", preparedStatement.toString()));
            preparedStatement.executeUpdate();

            ResultSet resultSet = preparedStatement.getGeneratedKeys();
            if (resultSet.next()) {
                return resultSet.getInt(1);
            }

            throw new SQLException("Key was not generated by the database.");
        } catch (SQLException e) {
            throw handleException(sql, e);
        }
    }

    /**
     * Executes a query with no preparation function, and maps to the provided IRowMapper function.
     * @param sql SQL to execute
     * @param rowMapper Function with context of ResultSet to return T
     * @return List of T
     * @param <T> Type of object to return in a list
     */
    protected <T> List<T> executeQuery(String sql, IRowMapper<T> rowMapper) {
        return executeQuery(sql, preparedStatement -> {}, rowMapper);
    }

    /**
     * Executes a query with a preparation function, and maps to the provided IRowMapper function.
     * @param sql SQL to execute
     * @param preparedStatementBinder Function with context of the PreparedStatement
     * @param rowMapper Function with context of ResultSet to return T
     * @return List of T
     * @param <T> Type of object to return in a list
     */
    protected <T> List<T> executeQuery(String sql, IPreparedStatementBinder preparedStatementBinder, IRowMapper<T> rowMapper) {
        List<T> results = new ArrayList<>();
        Connection connection = SqliteConnection.getConnection();
        try (PreparedStatement preparedStatement = connection.prepareStatement(sql)) {
            preparedStatementBinder.accept(preparedStatement);

            ResultSet resultSet = preparedStatement.executeQuery();
            while (resultSet.next()) {
                results.add(rowMapper.map(resultSet));
            }

            return results;
        } catch (SQLException e) {
            throw handleException(sql, e);
        }
    }

    /**
     * Shared method to handle all SQL exceptions
     * @param sql SQL to execute
     * @param e Exception raised
     */
    private RuntimeException handleException(String sql, Exception e) {
        logger.severe(String.format("Error executing SQL: %s", e.getMessage()));

        // TODO: more elegantly handle the error, i.e. don't throw here. Throwing will help identify problems during development though
        throw new RuntimeException("Database operation failed. See logs for info. ", e);
    }

    /**
     * Returns null if the List is empty
     * @return T as reference (can be a null reference)
     * @param <T> Type for List
     */
    public <T> T firstOrNull(List<T> list) {
        return list.isEmpty() ? null : list.getFirst();
    }
}
