package com.codependentvariables.aiandme.model.dao;

import com.codependentvariables.aiandme.database.IDatabaseEntity;
import com.codependentvariables.aiandme.database.IRowMapper;
import com.codependentvariables.aiandme.model.QuizTemplateQuestion;

import java.util.List;

public class SqliteQuizTemplateQuestionDAO extends BaseSqliteDAO implements IQuizTemplateQuestionDAO, IDatabaseEntity {
    private static final String schemaQuery = """
                CREATE TABLE IF NOT EXISTS quiz_template_questions (
                    id INTEGER PRIMARY KEY,
                    quiz_template_id INTEGER NOT NULL REFERENCES quiz_templates(id),
                    text VARCHAR NOT NULL,
                    image BLOB
                );
            """;

    private static final String seedDataQuery = """
                INSERT INTO quiz_template_questions (quiz_template_id, text) VALUES (1, 'Solve the Equation; 2 + 3 * 6 =');
                INSERT INTO quiz_template_questions (quiz_template_id, text) VALUES (1, 'Solve the Equation; 4 + 5 - 4 / 2 =');
                INSERT INTO quiz_template_questions (quiz_template_id, text) VALUES (1, 'Solve the Equation; 3 * 4 - 6 / 2 =');
                INSERT INTO quiz_template_questions (quiz_template_id, text) VALUES (1, 'Solve the Equation; 4 - ( 2 * 4 ) / 2 + 6 =');
                INSERT INTO quiz_template_questions (quiz_template_id, text) VALUES (1, 'Solve the Equation; ( 81 / 9 ) + 2 * 4 =');
                INSERT INTO quiz_template_questions (quiz_template_id, text) VALUES (1, 'Solve the Equation; 14 / 2 * ( 5 + 2 ) =');
                INSERT INTO quiz_template_questions (quiz_template_id, text) VALUES (1, 'Solve the Equation; 50 / 4 * 2 + (17 + 8) =');
                INSERT INTO quiz_template_questions (quiz_template_id, text) VALUES (1, 'Solve the Equation; 6 * (2 + 3^2) - 4 =');
                INSERT INTO quiz_template_questions (quiz_template_id, text) VALUES (1, 'Solve the Equation; 42 / ( ( 141 / ( 11 * 4 + 3) ) + 4 ) =');
                INSERT INTO quiz_template_questions (quiz_template_id, text) VALUES (1, 'Solve the Equation; 8 * 6 + 12 - ( 4^2 + (3^4 / 40.5 ) * 5 ) =');
                INSERT INTO quiz_template_questions (quiz_template_id, text) VALUES (2, 'Identify the missing value; 3, 7, 11, ?, 19, 23');
                INSERT INTO quiz_template_questions (quiz_template_id, text) VALUES (2, 'Identify the missing value; 1, ?, -2, -6, -14, -30');
                INSERT INTO quiz_template_questions (quiz_template_id, text) VALUES (2, 'Identify the missing value; 60, 74.5, ?, 103.5, 118');
                INSERT INTO quiz_template_questions (quiz_template_id, text) VALUES (2, 'Identify the missing value; 4, ?, 36, 108, 324');
                INSERT INTO quiz_template_questions (quiz_template_id, text) VALUES (2, 'Identify the missing value; 5, 7, 12, 19, ?, 50, 81');
                INSERT INTO quiz_template_questions (quiz_template_id, text) VALUES (2, 'Identify the missing value; 2, ?, 4, 6, 8, 12, 18, 26, 38');
                INSERT INTO quiz_template_questions (quiz_template_id, text) VALUES (2, 'Identify the missing value; 11, 13, 17, 19, 23, ?, 31');
                INSERT INTO quiz_template_questions (quiz_template_id, text) VALUES (2, 'Identify the missing value; 2, ?, -2, 2, -4, -8, 32, -256');
                INSERT INTO quiz_template_questions (quiz_template_id, text) VALUES (2, 'Identify the missing value; 1, 4, 9, 16, ?, 32');
                INSERT INTO quiz_template_questions (quiz_template_id, text) VALUES (2, 'Identify the missing value; 15, ?, 7.5, 5, 3, 1.875');
                INSERT INTO quiz_template_questions (quiz_template_id, text) VALUES (3, 'Identify the Outlier amongst these words; Apple, Orange, Carrot, Banana, Lemon');
                INSERT INTO quiz_template_questions (quiz_template_id, text) VALUES (3, 'Identify the Outlier amongst these words; Plate, Brisket, Flank, Jowl, Scale');
                INSERT INTO quiz_template_questions (quiz_template_id, text) VALUES (3, 'Identify the Outlier amongst these words; France, Spain, Bulgaria, Peru, Iceland');
                INSERT INTO quiz_template_questions (quiz_template_id, text) VALUES (3, 'Identify the Outlier amongst these words; Puffer, Hourglass, Bream, Flathead, Mullet');
                INSERT INTO quiz_template_questions (quiz_template_id, text) VALUES (3, 'Identify the Outlier amongst these words; Pacific, Indian, Atlantic, Arctic, Amazon');
                INSERT INTO quiz_template_questions (quiz_template_id, text) VALUES (3, 'Identify the Outlier amongst these words; Aquifer, Mountain, Tor, Mesa, Butte');
                INSERT INTO quiz_template_questions (quiz_template_id, text) VALUES (3, 'Identify the Outlier amongst these words; Maple, Bamboo, Willow, Sycamore, Birch');
                INSERT INTO quiz_template_questions (quiz_template_id, text) VALUES (3, 'Identify the Outlier amongst these words; Frog, Turtle, Crocodile, Chameleon, Snake');
                INSERT INTO quiz_template_questions (quiz_template_id, text) VALUES (3, 'Identify the Outlier amongst these words; Radio, Infrared, Gamma, Microwave, Remote');
                INSERT INTO quiz_template_questions (quiz_template_id, text) VALUES (3, 'Identify the Outlier amongst these words; Lungs, Heart, Muscles, Skin, Stomach');
                INSERT INTO quiz_template_questions (quiz_template_id, text) VALUES (3, 'Identify the Outlier amongst these words; Bus, Car, Bicycle, Plane, Skateboard');
                INSERT INTO quiz_template_questions (quiz_template_id, text) VALUES (3, 'Identify the Outlier amongst these words; Gold, Iron, Copper, Aluminum, Lead');
                INSERT INTO quiz_template_questions (quiz_template_id, text) VALUES (4, 'The masked man sat upon the tallest untouched structure, watching the city around him burn. From this high he could hear only the sounds of crackling fire, punctuated by his own ragged breaths. Uldal approach from behind, cautious not to alert the man of his presence. He turns regardless, empty eyes calling to Uldal, not an ounce of sorrow or pain to be seen.\n\n“Now you stop?” Uldal Croaks, his breath ragged from the journey up. “Of all the opportunities, why now?”\n\n“Because the job is done, I can finally rest” The Man turns back towards the blazing city, not caring of Uldal’s approach.\n\n“Was it worth it, all those lost in your rampage? Did you even think about the price of your vengeance?”\n\n“At one stage I might have, but should the circumstances require it, i would pay the cost tenfold”\n\n“You’re a monster” Uldal cuts the man off "You're a tyrant, you're worse than anything your brother ever was”\n\n“Perhaps you are correct, but for now I am just tired. So please, let me rest”\n\nThe man remains where he sits, watching the fires dwindle to coal and ash, as Uldal slowly makes for the long journey back down.\n\nBased on the above passage, what emotion would best describe what the masked man is feeling?');
                INSERT INTO quiz_template_questions (quiz_template_id, text) VALUES (4, 'The masked man sat upon the tallest untouched structure, watching the city around him burn. From this high he could hear only the sounds of crackling fire, punctuated by his own ragged breaths. Uldal approach from behind, cautious not to alert the man of his presence. He turns regardless, empty eyes calling to Uldal, not an ounce of sorrow or pain to be seen.\n\n“Now you stop?” Uldal Croaks, his breath ragged from the journey up. “Of all the opportunities, why now?”\n\n“Because the job is done, I can finally rest” The Man turns back towards the blazing city, not caring of Uldal’s approach.\n\n“Was it worth it, all those lost in your rampage? Did you even think about the price of your vengeance?”\n\n“At one stage I might have, but should the circumstances require it, i would pay the cost tenfold”\n\n“You’re a monster” Uldal cuts the man off "You're a tyrant, you're worse than anything your brother ever was”\n\n“Perhaps you are correct, but for now I am just tired. So please, let me rest”\n\nThe man remains where he sits, watching the fires dwindle to coal and ash, as Uldal slowly makes for the long journey back down.\n\nBased on the above passage, why did the mask man ascend to the tallest structure?');
                INSERT INTO quiz_template_questions (quiz_template_id, text) VALUES (4, 'The masked man sat upon the tallest untouched structure, watching the city around him burn. From this high he could hear only the sounds of crackling fire, punctuated by his own ragged breaths. Uldal approach from behind, cautious not to alert the man of his presence. He turns regardless, empty eyes calling to Uldal, not an ounce of sorrow or pain to be seen.\n\n“Now you stop?” Uldal Croaks, his breath ragged from the journey up. “Of all the opportunities, why now?”\n\n“Because the job is done, I can finally rest” The Man turns back towards the blazing city, not caring of Uldal’s approach.\n\n“Was it worth it, all those lost in your rampage? Did you even think about the price of your vengeance?”\n\n“At one stage I might have, but should the circumstances require it, i would pay the cost tenfold”\n\n“You’re a monster” Uldal cuts the man off "You're a tyrant, you're worse than anything your brother ever was”\n\n“Perhaps you are correct, but for now I am just tired. So please, let me rest”\n\nThe man remains where he sits, watching the fires dwindle to coal and ash, as Uldal slowly makes for the long journey back down.\n\nBased on the above passage, what theme is most strongly represented?');
                INSERT INTO quiz_template_questions (quiz_template_id, text) VALUES (4, 'The masked man sat upon the tallest untouched structure, watching the city around him burn. From this high he could hear only the sounds of crackling fire, punctuated by his own ragged breaths. Uldal approach from behind, cautious not to alert the man of his presence. He turns regardless, empty eyes calling to Uldal, not an ounce of sorrow or pain to be seen.\n\n“Now you stop?” Uldal Croaks, his breath ragged from the journey up. “Of all the opportunities, why now?”\n\n“Because the job is done, I can finally rest” The Man turns back towards the blazing city, not caring of Uldal’s approach.\n\n“Was it worth it, all those lost in your rampage? Did you even think about the price of your vengeance?”\n\n“At one stage I might have, but should the circumstances require it, i would pay the cost tenfold”\n\n“You’re a monster” Uldal cuts the man off "You're a tyrant, you're worse than anything your brother ever was”\n\n“Perhaps you are correct, but for now I am just tired. So please, let me rest”\n\nThe man remains where he sits, watching the fires dwindle to coal and ash, as Uldal slowly makes for the long journey back down.\n\nBased on the above passage, what does the masked man’s desire to “rest” most likely symbolise?');
                INSERT INTO quiz_template_questions (quiz_template_id, text) VALUES (4, 'The masked man sat upon the tallest untouched structure, watching the city around him burn. From this high he could hear only the sounds of crackling fire, punctuated by his own ragged breaths. Uldal approach from behind, cautious not to alert the man of his presence. He turns regardless, empty eyes calling to Uldal, not an ounce of sorrow or pain to be seen.\n\n“Now you stop?” Uldal Croaks, his breath ragged from the journey up. “Of all the opportunities, why now?”\n\n“Because the job is done, I can finally rest” The Man turns back towards the blazing city, not caring of Uldal’s approach.\n\n“Was it worth it, all those lost in your rampage? Did you even think about the price of your vengeance?”\n\n“At one stage I might have, but should the circumstances require it, i would pay the cost tenfold”\n\n“You’re a monster” Uldal cuts the man off "You're a tyrant, you're worse than anything your brother ever was”\n\n“Perhaps you are correct, but for now I am just tired. So please, let me rest”\n\nThe man remains where he sits, watching the fires dwindle to coal and ash, as Uldal slowly makes for the long journey back down.\n\nBased on the above passage, how does the masked man’s reference to “a negligible cost” shape the reader’s understanding of him?');
                INSERT INTO quiz_template_questions (quiz_template_id, text) VALUES (4, '"Couldn't intercept a wired signal, that was what pop always said. Radio waves and wireless, well any old hoon could grab. And as deciphering got easier, societal trust waned, and the quick pivot led us here.” Zell speaks, waving his hands towards the mat of wires strung from building to building, uncaring whether the words fell on Brehm's deft ears. He eyes both entrances to the alleyway, before returning to the canopy of cables hanging above. “Makes a great bird nest though"\n\nHe speaks with an optimistic rhythm, as though singing each word to match a song stuck in his head. With a quick “yip”, Zell hops atop a dented garbage can, as he awkwardly wrestles out a large boxy device from his already oversized coat pockets.\n\n"This, agh" the box snags on his pocket lip, threatening to tumble from his hands. "This though, this little lad makes wireless feel like a goddamn fort."\n\nPressing a button on the side, the device splits in two, a spiked groove runs down the middle, perfect for closing around a cable. Taking time to follow the tangle with his eyes, Zell hones in on his target, reaching up to snap the box in place. A whirl of motors, followed by a string of soft beeps matching the rhythm Zell hummed to before, indicate the device is functioning.\n\n“Easy as,” Zell turns to Brehm, leaping off the bin. “Just swing back whenever with the corresponding thumb drive, and you'll have access to read all transmissions along this route.”\n\nBrehm nods, pulls out a wad of cash, the monotone words leave his mouth whilst he counts.\n\n“Boss said to give ya half pay”\n\nHe thumbs through the money.\n\n“No incidents. No risk bonus. So here’s the service fee”\n\n“Are you kidding? The service is free, it's the patent on the box you're paying for. Half price means half data. So, you want me to scramble every other packet?\n\n“Fine” Brehm grunts “But Cadrin ain't gonna like paying full”\n\n“Ptttttfff, well tell Cadrin to do it himself if he wants to negotiate after the jobs done”\n\nZell snatches the remainder of his money from Brehm’s thick hands, then spins, and struts down the alley, still half-singing his words. “Pleasure doing business with ya”\n\nBased on the above passage, what belief does Zell's “Pop” have about wired signals?');
                INSERT INTO quiz_template_questions (quiz_template_id, text) VALUES (4, '"Couldn't intercept a wired signal, that was what pop always said. Radio waves and wireless, well any old hoon could grab. And as deciphering got easier, societal trust waned, and the quick pivot led us here.” Zell speaks, waving his hands towards the mat of wires strung from building to building, uncaring whether the words fell on Brehm's deft ears. He eyes both entrances to the alleyway, before returning to the canopy of cables hanging above. “Makes a great bird nest though"\n\nHe speaks with an optimistic rhythm, as though singing each word to match a song stuck in his head. With a quick “yip”, Zell hops atop a dented garbage can, as he awkwardly wrestles out a large boxy device from his already oversized coat pockets.\n\n"This, agh" the box snags on his pocket lip, threatening to tumble from his hands. "This though, this little lad makes wireless feel like a goddamn fort."\n\nPressing a button on the side, the device splits in two, a spiked groove runs down the middle, perfect for closing around a cable. Taking time to follow the tangle with his eyes, Zell hones in on his target, reaching up to snap the box in place. A whirl of motors, followed by a string of soft beeps matching the rhythm Zell hummed to before, indicate the device is functioning.\n\n“Easy as,” Zell turns to Brehm, leaping off the bin. “Just swing back whenever with the corresponding thumb drive, and you'll have access to read all transmissions along this route.”\n\nBrehm nods, pulls out a wad of cash, the monotone words leave his mouth whilst he counts.\n\n“Boss said to give ya half pay”\n\nHe thumbs through the money.\n\n“No incidents. No risk bonus. So here’s the service fee”\n\n“Are you kidding? The service is free, it's the patent on the box you're paying for. Half price means half data. So, you want me to scramble every other packet?\n\n“Fine” Brehm grunts “But Cadrin ain’t gonna like paying full”\n\n“Ptttttfff, well tell Cadrin to do it himself if he wants to negotiate after the jobs done”\n\nZell snatches the remainder of his money from Brehm’s thick hands, then spins, and struts down the alley, still half-singing his words. “Pleasure doing business with ya”\n\nBased on the above passage, what is the main function of Zell’s device?');
                INSERT INTO quiz_template_questions (quiz_template_id, text) VALUES (4, '"Couldn't intercept a wired signal, that was what pop always said. Radio waves and wireless, well any old hoon could grab. And as deciphering got easier, societal trust waned, and the quick pivot led us here.” Zell speaks, waving his hands towards the mat of wires strung from building to building, uncaring whether the words fell on Brehm's deft ears. He eyes both entrances to the alleyway, before returning to the canopy of cables hanging above. “Makes a great bird nest though"\n\nHe speaks with an optimistic rhythm, as though singing each word to match a song stuck in his head. With a quick “yip”, Zell hops atop a dented garbage can, as he awkwardly wrestles out a large boxy device from his already oversized coat pockets.\n\n"This, agh" the box snags on his pocket lip, threatening to tumble from his hands. "This though, this little lad makes wireless feel like a goddamn fort."\n\nPressing a button on the side, the device splits in two, a spiked groove runs down the middle, perfect for closing around a cable. Taking time to follow the tangle with his eyes, Zell hones in on his target, reaching up to snap the box in place. A whirl of motors, followed by a string of soft beeps matching the rhythm Zell hummed to before, indicate the device is functioning.\n\n“Easy as,” Zell turns to Brehm, leaping off the bin. “Just swing back whenever with the corresponding thumb drive, and you'll have access to read all transmissions along this route.”\n\nBrehm nods, pulls out a wad of cash, the monotone words leave his mouth whilst he counts.\n\n“Boss said to give ya half pay”\n\nHe thumbs through the money.\n\n“No incidents. No risk bonus. So here’s the service fee”\n\n“Are you kidding? The service is free, it's the patent on the box you're paying for. Half price means half data. So, you want me to scramble every other packet?\n\n“Fine” Brehm grunts “But Cadrin ain’t gonna like paying full”\n\n“Ptttttfff, well tell Cadrin to do it himself if he wants to negotiate after the jobs done”\n\nZell snatches the remainder of his money from Brehm’s thick hands, then spins, and struts down the alley, still half-singing his words. “Pleasure doing business with ya”\n\nBased on the above passage, why might Zell be described as “half-singing” while working?');
                INSERT INTO quiz_template_questions (quiz_template_id, text) VALUES (4, '"Couldn't intercept a wired signal, that was what pop always said. Radio waves and wireless, well any old hoon could grab. And as deciphering got easier, societal trust waned, and the quick pivot led us here.” Zell speaks, waving his hands towards the mat of wires strung from building to building, uncaring whether the words fell on Brehm's deft ears. He eyes both entrances to the alleyway, before returning to the canopy of cables hanging above. “Makes a great bird nest though"\n\nHe speaks with an optimistic rhythm, as though singing each word to match a song stuck in his head. With a quick “yip”, Zell hops atop a dented garbage can, as he awkwardly wrestles out a large boxy device from his already oversized coat pockets.\n\n"This, agh" the box snags on his pocket lip, threatening to tumble from his hands. "This though, this little lad makes wireless feel like a goddamn fort."\n\nPressing a button on the side, the device splits in two, a spiked groove runs down the middle, perfect for closing around a cable. Taking time to follow the tangle with his eyes, Zell hones in on his target, reaching up to snap the box in place. A whirl of motors, followed by a string of soft beeps matching the rhythm Zell hummed to before, indicate the device is functioning.\n\n“Easy as,” Zell turns to Brehm, leaping off the bin. “Just swing back whenever with the corresponding thumb drive, and you'll have access to read all transmissions along this route.”\n\nBrehm nods, pulls out a wad of cash, the monotone words leave his mouth whilst he counts.\n\n“Boss said to give ya half pay”\n\nHe thumbs through the money.\n\n“No incidents. No risk bonus. So here’s the service fee”\n\n“Are you kidding? The service is free, it's the patent on the box you're paying for. Half price means half data. So, you want me to scramble every other packet?\n\n“Fine” Brehm grunts “But Cadrin ain’t gonna like paying full”\n\n“Ptttttfff, well tell Cadrin to do it himself if he wants to negotiate after the jobs done”\n\nZell snatches the remainder of his money from Brehm’s thick hands, then spins, and struts down the alley, still half-singing his words. “Pleasure doing business with ya”\n\nBased on the above passage, what does the phrase “any old hoon could grab” infern when describing wireless signals?');
                INSERT INTO quiz_template_questions (quiz_template_id, text) VALUES (4, '"Couldn't intercept a wired signal, that was what pop always said. Radio waves and wireless, well any old hoon could grab. And as deciphering got easier, societal trust waned, and the quick pivot led us here.” Zell speaks, waving his hands towards the mat of wires strung from building to building, uncaring whether the words fell on Brehm's deft ears. He eyes both entrances to the alleyway, before returning to the canopy of cables hanging above. “Makes a great bird nest though"\n\nHe speaks with an optimistic rhythm, as though singing each word to match a song stuck in his head. With a quick “yip”, Zell hops atop a dented garbage can, as he awkwardly wrestles out a large boxy device from his already oversized coat pockets.\n\n"This, agh" the box snags on his pocket lip, threatening to tumble from his hands. "This though, this little lad makes wireless feel like a goddamn fort."\n\nPressing a button on the side, the device splits in two, a spiked groove runs down the middle, perfect for closing around a cable. Taking time to follow the tangle with his eyes, Zell hones in on his target, reaching up to snap the box in place. A whirl of motors, followed by a string of soft beeps matching the rhythm Zell hummed to before, indicate the device is functioning.\n\n“Easy as,” Zell turns to Brehm, leaping off the bin. “Just swing back whenever with the corresponding thumb drive, and you'll have access to read all transmissions along this route.”\n\nBrehm nods, pulls out a wad of cash, the monotone words leave his mouth whilst he counts.\n\n“Boss said to give ya half pay”\n\nHe thumbs through the money.\n\n“No incidents. No risk bonus. So here’s the service fee”\n\n“Are you kidding? The service is free, it's the patent on the box you're paying for. Half price means half data. So, you want me to scramble every other packet?\n\n“Fine” Brehm grunts “But Cadrin ain’t gonna like paying full”\n\n“Ptttttfff, well tell Cadrin to do it himself if he wants to negotiate after the jobs done”\n\nZell snatches the remainder of his money from Brehm’s thick hands, then spins, and struts down the alley, still half-singing his words. “Pleasure doing business with ya”\n\nBased on the above passage, what theme does Zell’s attitude most strongly symbolise?');
            """;

    @Override
    public String getSchemaQuery() { return schemaQuery; }

    @Override
    public String getSeedDataQuery() {
        return seedDataQuery;
    }

    private static final IRowMapper<QuizTemplateQuestion> MAPPER = (rs) -> {
        QuizTemplateQuestion question = new QuizTemplateQuestion(
                rs.getInt("quiz_template_id"),
                rs.getString("text"),
                rs.getBytes("image")
        );
        question.setId(rs.getInt("id"));
        return question;
    };

    @Override
    public void addQuestion(QuizTemplateQuestion question) {
        final String query = "INSERT INTO quiz_template_questions(quiz_template_id, text, image) VALUES(?, ?, ?)";
        var id = executeSqlWithGeneratedKeys(query, stmt -> {
            stmt.setInt(1, question.getQuizTemplateId());
            stmt.setString(2, question.getText());
            stmt.setBytes(3, question.getImage());
        });
        question.setId(id);
    }

    @Override
    public void updateQuestion(QuizTemplateQuestion question) {
        final String query = "UPDATE quiz_template_questions SET quiz_template_id = ?, text = ?, image = ? WHERE id = ?";
        executeSql(query, stmt -> {
            stmt.setInt(1, question.getQuizTemplateId());
            stmt.setString(2, question.getText());
            stmt.setBytes(3, question.getImage());
            stmt.setInt(4, question.getId());
        });
    }

    @Override
    public void deleteQuestion(QuizTemplateQuestion question) {
        final String query = "DELETE FROM quiz_template_questions WHERE id = ?";
        executeSql(query, stmt -> stmt.setInt(1, question.getId()));
    }

    @Override
    public QuizTemplateQuestion get(int id) {
        final String query = "SELECT * FROM quiz_template_questions WHERE id = ? LIMIT 1";
        List<QuizTemplateQuestion> results = executeQuery(query, stmt -> stmt.setInt(1, id), MAPPER);
        return firstOrNull(results);
    }

    @Override
    public List<QuizTemplateQuestion> getQuestionsByTemplate(int quizTemplateId) {
        final String query = "SELECT * FROM quiz_template_questions WHERE quiz_template_id = ?";
        return executeQuery(query, stmt -> stmt.setInt(1, quizTemplateId), MAPPER);
    }
}

