name: Build and test
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: maven

      - name: Install xvfb (Virtual Display)
        run: sudo apt-get update && sudo apt-get install -y libgl1 xvfb libgtk-3-0
        shell: bash

      - name: Run tests
        run: xvfb-run mvn test --batch-mode

  build:
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os-profile: [windows, linux, mac]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: maven

      - name: Package Artifact (${{ matrix.os-profile }})
        run: |
          mvn package -DskipTests -P${{ matrix.os-profile }}
          mkdir staging
          mv target/*-with-dependencies.jar staging/aiandme-${{ matrix.os-profile }}.jar

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: aiandme-${{ matrix.os-profile }}
          path: staging/

  javadoc:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: maven

      - name: Create Javadoc
        run: mvn clean compile javadoc:javadoc

      - name: Publish Javadoc
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: target/docs/javadoc
