name: Build and test
on: push

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: maven

      - name: 1. Compile
        run: mvn compile

      - name: 2. Test
        run: mvn test --batch-mode

      - name: 3. Build Windows Artifact
        run: mvn package -DskipTests -Pwindows
      - name: Store Windows Artifact
        run: mv target/*-with-dependencies.jar staging/aiandme-windows.jar

      - name: 4. Build Linux Artifact
        run: mvn package -DskipTests -Plinux
      - name: Store Linux Artifact
        run: mv target/*-with-dependencies.jar staging/aiandme-linux.jar

      - name: 5. Build Mac Artifact
        run: mvn package -DskipTests -Pmac
      - name: Store Mac Artifact
        run: mv target/*-with-dependencies.jar staging/aiandme-mac.jar

      - name: 6. Upload All Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: multiplatform-builds
          path: staging/